apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: notes-cloud
  labels:
    app: frontend
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: notes-cloud-platform
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP