apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: notes-cloud
  labels:
    app: frontend
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: notes-cloud-platform
data:
  config.js: |
    window.__APP_CONFIG__ = {
        API_BASE_URL: "http://localhost:8090/api/v1",
        GATEWAY_BASE_URL: "http://localhost:8090",
        WS_REMINDERS_URL: "ws://localhost:8090/ws"
    };