apiVersion: v1
kind: Secret
metadata:
  name: internal-token-secret
  namespace: notes-cloud
  labels:
    app.kubernetes.io/part-of: notes-cloud-platform
type: Opaque
stringData:
  INTERNAL_SERVICE_TOKEN: "3NyCMVUFmGzRafIiaeZKZaVJO5bvXsO27IbC5kM0ayxIfE5xsM_GuhRAS2k6r2uf"