apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: notes-cloud
  labels:
    app.kubernetes.io/part-of: notes-cloud-platform
type: Opaque
stringData:
  JWT_SECRET: "X9kP2mQvR8wL4nBc7yHjT3fAeU6sD1gZpY5tN0xKmW"
