apiVersion: v1
kind: ConfigMap
metadata:
  name: reminder-service-config
  namespace: notes-cloud
  labels:
    app: reminder-service
    app.kubernetes.io/name: reminder-service
    app.kubernetes.io/part-of: notes-cloud-platform
data:
  SPRING_PROFILES_ACTIVE: "local"