apiVersion: v1
kind: Service
metadata:
  name: reminder-service
  namespace: notes-cloud
  labels:
    app: reminder-service
    app.kubernetes.io/name: reminder-service
    app.kubernetes.io/part-of: notes-cloud-platform
spec:
  type: ClusterIP
  selector:
    app: reminder-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084
      protocol: TCP