apiVersion: v1
kind: Secret
metadata:
  name: reminder-service-secret
  namespace: notes-cloud
  labels:
    app: reminder-service
    app.kubernetes.io/name: reminder-service
    app.kubernetes.io/part-of: notes-cloud-platform
type: Opaque
stringData:
  POSTGRES_PASSWORD: "notes_cloud_password"