apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: notes-cloud
  labels:
    app: api-gateway
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: notes-cloud-platform
data:
  SERVER_PORT: "8090"

  AUTH_SERVICE_URL: "http://auth-service:8080"
  NOTES_SERVICE_URL: "http://notes-service:8082"
  TODO_SERVICE_URL: "http://todo-service:8085"
  REMINDER_SERVICE_URL: "http://reminder-service:8084"
  SHARING_SERVICE_URL: "http://sharing-service:8083"

  FRONTEND_ORIGIN: "http://localhost:5173"
  ALLOWED_ORIGINS: "http://localhost:5173,http://localhost:3000,http://localhost:4173"

  JWT_VALIDATION_URL: "http://auth-service:8080/internal/auth/validate"