apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: notes-cloud
  labels:
    app: api-gateway
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: notes-cloud-platform
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 8090
      targetPort: 8090
      protocol: TCP