apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  namespace: notes-cloud
  labels:
    app: api-gateway
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: notes-cloud-platform
type: Opaque
stringData:
  INTERNAL_SERVICE_TOKEN: "change-this-in-real-env"