apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: notes-cloud
  labels:
    app: api-gateway
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: notes-cloud-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        app.kubernetes.io/name: api-gateway
        app.kubernetes.io/part-of: notes-cloud-platform
    spec:
      containers:
        - name: api-gateway
          image: hristo12319/notes-cloud-api-gateway:v1
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8090
              protocol: TCP

          envFrom:
            - configMapRef:
                name: api-gateway-config
            - configMapRef:
                name: jwt-config
            - secretRef:
                name: jwt-secret

          env:
            - name: INTERNAL_SERVICE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: internal-token-secret
                  key: INTERNAL_SERVICE_TOKEN

          readinessProbe:
            httpGet:
              path: /api/readyz
              port: 8090
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /api/healthz
              port: 8090
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi