apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: notes-cloud
  labels:
    app: auth-service
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: notes-cloud-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
        app.kubernetes.io/name: auth-service
        app.kubernetes.io/part-of: notes-cloud-platform
    spec:
      containers:
        - name: auth-service
          image: notes-cloud-auth-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP

          env:
            - name: CONFIG_FILE
              value: "/etc/config/config.json"
            - name: DB_PASSWORD_FILE
              value: "/etc/secrets/db-password"

          volumeMounts:
            - name: config
              mountPath: /etc/config
              readOnly: true
            - name: secrets
              mountPath: /etc/secrets
              readOnly: true

          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 20

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi

      volumes:
        - name: config
          configMap:
            name: auth-service-config
        - name: secrets
          secret:
            secretName: auth-service-secret
