apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: notes-cloud
  labels:
    app: auth-service
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: notes-cloud-platform
type: Opaque
stringData:
  db-password: "notes_cloud_password"
