apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: notes-cloud
  labels:
    app: auth-service
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: notes-cloud-platform
type: Opaque
stringData:
  DB_PASSWORD: "notes_cloud_password"
  JWT_SECRET: "X9kP2mQvR8wL4nBc7yHjT3fAeU6sD1gZpY5tN0xKmW"
  REFRESH_TOKEN_SECRET: "Bw7tN8xKmP2qL9vR4hJcY5fAeU3sD6gZpX0nW1yHjT"
