apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-service-config
  namespace: notes-cloud
  labels:
    app: todo-service
    app.kubernetes.io/name: todo-service
    app.kubernetes.io/part-of: notes-cloud-platform
data:
  SERVER_PORT: "8085"

  DB_HOST: "postgres"
  DB_PORT: "5432"
  POSTGRES_DB: "notes_cloud"
  POSTGRES_USER: "notes_cloud_user"

  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"