apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-service
  namespace: notes-cloud
  labels:
    app: todo-service
    app.kubernetes.io/name: todo-service
    app.kubernetes.io/part-of: notes-cloud-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-service
  template:
    metadata:
      labels:
        app: todo-service
        app.kubernetes.io/name: todo-service
        app.kubernetes.io/part-of: notes-cloud-platform
    spec:
      containers:
        - name: todo-service
          image: hristo12319/notes-cloud-todo-service:v1
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 8085
              protocol: TCP

          envFrom:
            - configMapRef:
                name: todo-service-config
            - secretRef:
                name: todo-service-secret

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
