apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-service-config
  namespace: notes-cloud
  labels:
    app: todo-service
    app.kubernetes.io/name: todo-service
    app.kubernetes.io/part-of: notes-cloud-platform
data:
  SPRING_APPLICATION_NAME: "todo-service"
  SPRING_PROFILES_ACTIVE: "local"
  SERVER_PORT: "8085"