apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: notes-cloud
  labels:
    app: todo-service
    app.kubernetes.io/name: todo-service
    app.kubernetes.io/part-of: notes-cloud-platform
spec:
  type: ClusterIP
  selector:
    app: todo-service
  ports:
    - name: http
      port: 8085
      targetPort: 8085
      protocol: TCP