apiVersion: v1
kind: Secret
metadata:
  name: todo-service-secret
  namespace: notes-cloud
  labels:
    app: todo-service
    app.kubernetes.io/name: todo-service
    app.kubernetes.io/part-of: notes-cloud-platform
type: Opaque
stringData:
  DB_PASSWORD: "notes_cloud_password"