apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: notes-cloud
  labels:
    app: postgres
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: notes-cloud-platform
data:
  POSTGRES_DB: "notes_cloud"
  POSTGRES_USER: "notes_cloud_user"
  PGDATA: "/var/lib/postgresql/data/pgdata"