apiVersion: v1
kind: Secret
metadata:
  name: sharing-service-secret
  namespace: notes-cloud
  labels:
    app: sharing-service
    app.kubernetes.io/name: sharing-service
    app.kubernetes.io/part-of: notes-cloud-platform
type: Opaque
stringData:
  DB_PASSWORD: "notes_cloud_password"