apiVersion: v1
kind: ConfigMap
metadata:
  name: notes-service-config
  namespace: notes-cloud
  labels:
    app: notes-service
    app.kubernetes.io/name: notes-service
    app.kubernetes.io/part-of: notes-cloud-platform
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8082"